source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PaperCollectionView_Example', :exclusive => true do
  pod 'PaperCollectionView', :path => '../'
end

target 'PaperCollectionView_Tests', :exclusive => true do
  pod 'PaperCollectionView', :path => '../'

  
end
